### ISSUE TITLE
Нет функции «автомасштаб по Y»

### ISSUE THREAD

**Issue by Mazdaywik** [klu4vanya/Practice_2.0#1]
В задании было требование галочки «автомасштаб по оси Y».

Если эта галочка установлена, то поле ввода диапазона для Y затеняется (disable), границы устанавливаются автоматически.

**Comment by klu4vanya** [comment]
понял, поправлю

ср, 6 окт. 2021 г. в 14:08, Alexander Konovalov ***@***.***>:

**Comment by Mazdaywik** [comment]
Функция есть, но не работает:
![image](https://user-images.githubusercontent.com/1309859/136252115-3cff75e0-d45e-47c6-91e6-f54fd4bd08ec.png)
Для данной функции диапазон по Y должен быть от −1 до +1. Или (с 10%-ным запасом): от −1,1 до +1,1.

**Comment by klu4vanya** [comment]
Я просто не очень могу понять, в чем заключается эта функция. В том, что
она должна включать определенное значение, например я по дефолту поставил
-10 ,10 или как?

Ср, 6 окт. 2021 г. в 20:17, Alexander Konovalov ***@***.***>:

**Comment by klu4vanya** [comment]
Или же она должна выбирать максимум и минимум Y?

Ср, 6 окт. 2021 г. в 20:19, ваня клю4ник ***@***.***>:

**Comment by Mazdaywik** [comment]
Для точек в диапазоне по X она должна найти наименьшее и наибольшее значение Y и выбрать соответствующий масштаб. Я бы посоветовал добавлять по 5 % сверху и снизу, чтобы края графика не упирались в края рисунка. Т.е. если Ymax=5,0, Ymin=−3,0, то

|Ymax−Ymin| = 8,0
5 % × 8,0 = 0,4
Ymax′ = Ymax + 0,4 = 5,4
Ymin′ = Ymin − 0,4 = −3,4

Вот так как-то.

**Comment by Mazdaywik** [comment]
Надо было в описании коммита добавить `#1`, тогда бы он тут отобразился между комментариев.

**Comment by Mazdaywik** [comment]
```bash
git commit --amend "Исправлено автомасштабирование по Y (#1)"
git push -f
```

**Comment by klu4vanya** [comment]
Прописал эти команды

Сб, 9 окт. 2021 г. в 11:23, Alexander Konovalov ***@***.***>:

**Comment by Mazdaywik** [comment]
Странно, результата не видно.
